---
- name: Check for PostgreSQL Installation
  stat: path=/etc/init.d/postgresql
  register: POSTGRESQL_INSTALLED
  ignore_errors: True

- name: Add PostgreSQL Key
  shell: wget -q -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  when: POSTGRESQL_INSTALLED.stat.exists == false

- name: Add PostgreSQL Repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ CURRENT_UBUNTU_VERSION }}-pgdg main' state=present
  when: POSTGRESQL_INSTALLED.stat.exists == false

- name: Install PostgreSQL
  apt: pkg=postgresql update_cache=yes state=latest force=yes
  when: POSTGRESQL_INSTALLED.stat.exists == false
